#!/bin/bash
# This should be run after doing the following instructions.  After that, your system should be
# identical to Vinux/Lucid.  Note that you only use 'vinux' as the user name if you plan to
# create a Vinux ISO.  This script can also be used to restore your speech if your system
# stops talking after an upgrade.  See $LOGFILE for a full output of commands run
# in this script.
#
# 1. Download the Ubuntu Lucid Alpha 3 i386 iso and burn it to CD.
#
# 2. Boot from the CD, Press F5, select 'screen-reader' and boot the live CD.
#
# 3. Run the Ubuntu Installer, install the system to hard drive using 'vinux' as the username and
# password, then reboot.

LOGFILE="buildvinux.log"
INSTALL_VINUX_DESKTOP=""
ZIPCODE=""
while [ $# -gt 0 ]; do
    if [ $1 = "-l" ]; then
        shift
        if [ $# -lt 1 ]; then
    	    echo "Expecting log file name"
    	    exit 1
        fi
        LOGFILE=$1
    elif [ $1 = "-z" ]; then
        shift
        if [ $# -lt 1 ]; then
    	    echo "Expecting zipcode"
    	    exit 1
        fi
        ZIPCODE=$1
    elif [ $1 = "-d" ]; then
	INSTALL_VINUX_DESKTOP="no"
    elif [ $1 = "-D" ]; then
	INSTALL_VINUX_DESKTOP="yes"
    else
        echo "Unknown option $1"
        echo "Usage: restore_vinux_environment [-z zipcode] [-d|-D] [-l logFile]"
	echo "    -d  : Don't modify the Ubuntu desktop panels and background"
	echo "    -D  : Modify the Ubuntu desktop panels and background to like Vinux"
        exit 1
    fi
    shift
done

# Ask this first, so the user doesn't have to wait around listening carefully.
if [ "$ZIPCODE" = "" ]; then
    echo "Please enter your zipcode for Stormdragon's weather reporting using Orca+w"
    read ZIPCODE
fi
if [ "$INSTALL_VINUX_DESKTOP" = "" ]; then
    echo "Do you want to install Vinux destop panels and background image? [Y/n]"
    read ANSWER
    startsWithN=`echo $ANSWER | egrep -i '^[ \t]*n'`
    if [ "$startsWithN" != "" ]; then
	INSTALL_VINUX_DESKTOP="no"
    else
	INSTALL_VINUX_DESKTOP="yes"
    fi
fi

# Update /etc/apt/sources.list
echo "Updating software repositories..."
egrep -v 'vinux|remastersys' /etc/apt/sources.list > /tmp/vinux.tmp
echo '# Repositories supporting vinux packages.
deb http://ppa.launchpad.net/vinux/vinux-lucid/ubuntu lucid main
deb-src http://ppa.launchpad.net/vinux/vinux-lucid/ubuntu lucid main
deb http://ppa.launchpad.net/vinux/vinux-karmic/ubuntu karmic main
deb-src http://ppa.launchpad.net/vinux/vinux-karmic/ubuntu karmic main
deb http://www.geekconnection.org/remastersys/repository karmic/' >> /tmp/vinux.tmp
sed -i 's/^# *deb\(.*\) partner *$/deb\1 partner/
    s/^# *deb\(.*\)backports\(.*\)$/deb\1backports\2/' /tmp/vinux.tmp
sudo mv /tmp/vinux.tmp /etc/apt/sources.list

# Import the Vinux/Ubuntu Team repository key.
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EF2AFDCF > $LOGFILE 2>&1

# Update to the latest packages.
echo "Updating package list..."
sudo apt-get update >> $LOGFILE
echo "Upgrading all packages... This can take a few minutes."
echo "See $LOGFILE for progress."
sudo apt-get upgrade -y >> $LOGFILE

# Install some packages
sudo apt-get install -y gnome-orca speakup-source speakup-tools gparted yasr compizconfig-settings-manager speech-dispatcher-voxin acpi patch >> $LOGFILE
sudo apt-get install -y --force-yes remastersys >> $LOGFILE

# Enable speech
sudo /usr/bin/restorespeech -l $LOGFILE

# Edit speechd.conf to enable ibmtts.
if [ -f ~/.speech-dispatcher/conf/speechd.conf ]; then
    sed -i 's/#AddModule "ibmtts"/#AddModule "ibmtts"/' ~/.speech-dispatcher/conf/speechd.conf
fi

# Set Vinux keybindings, menus, desktop, etc
if [ "$INSTALL_VINUX_DESKTOP" = "yes" ]; then
    sudo /usr/bin/set_vinux_globals -l $LOGFILE -z $ZIPCODE
else
    sudo /usr/bin/set_vinux_globals -d -l $LOGFILE -z $ZIPCODE
fi

# Update our desktop to look like Vinux
if [ "$INSTALL_VINUX_DESKTOP" = "yes" ]; then
    cp -r /etc/skel/.gconf ~
fi
cp -r /etc/skel/.orca ~

echo "Done!  Reboot, and enjoy your new Vinux-like environment."
echo "Please report bugs to vinux-development@googlegroups.com"
