#!/bin/bash
# This program should run after buildvinux.  It will remove a bunch of
# applications to make more room on the CD ISO, and it will do other
# unhappy things to your system.  Unless you are trying to make a new
# release of Vinux, do not run this script.
#
# Run this script with sudo.

echo "Enter the release number, for example 3.0-alpha3"
read RELEASE
RELEASE_SPACES=`echo $RELEASE | sed 's/-/ /g'`

# Make space on system
echo "Removing applications to make room on the CD"
apt-get purge -y ubuntu-docs openoffice.org-common gnome-games-common gbrainy f-spot evolution-common evolution-data-server

# Next run remastersys and change the username to 'vinux' and the name of the
# CD and ISO file to 'Vinux-3.0-Alpha-3(.iso)'
sed -i "s/LIVEUSER=.*/LIVEUSER=\"vinux\"/
        s/LIVECDLABEL=.*/LIVECDLABEL=\"Vinux $RELEASE_SPACES\"/
        s/CUSTOMISO=.*/CUSTOMISO=\"vinux-$RELEASE.iso\"/" /etc/remastersys.conf

# Fix infinite loop in Ubiquity when installing with large fonts on small screens:
patch /usr/lib/ubiquity/ubiquity/frontend/gtk_ui.py /usr/share/vinux/ubiquity.patch

# Run remastersys in 'dist' mode from the Menu Launcher or the terminal. The
# iso should be in /home/remastersys in about 15-20 minutes.
echo "Building ISO..."
remastersys dist cdfs
unsquashfs -lls /home/remastersys/remastersys/ISOTMP/casper/filesystem.squashfs | grep -v " inodes " | grep -v "unsquashfs:" | awk '{print $3}' | grep -v "," > /tmp/size.tmp
a=0
for i in `cat /tmp/size.tmp`; do a=$(($a+$i)); done
echo $a > /home/remastersys/remastersys/ISOTMP/casper/filesystem.size

# Make the initial screen beep
sed -i 's/Vinux\(.*\)$/Vinux\1/' /home/remastersys/remastersys/ISOTMP/isolinux/isolinux.txt

remastersys dist iso
