#!/bin/bash
#
# This script can be run anytime to restore speech to a working state on a system.  
# Speech currently is often broken by system updates from Ubuntu. To run the script
# type: 'sudo configurespeech'.
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Stage 0 - Declare text colour/system bell functions

function black {
    tput setf 0   
}

function green {
    tput setf 2    
}

function blue {
    tput setf 3
}

function red {
    tput setf 4    
}

function white {
    tput setf 7
}

function reset {
    tput reset
}

function bell {
    echo -en "\007"    
}

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Activate volume control applet

sed -i 's/^OnlyShowIn=XFCE;$/OnlyShowIn=GNOME;XFCE;/' /etc/xdg/autostart/gnome-volume-control-applet.desktop

# Enable speakup

if [ "`grep 'speakup_soft start=1' /etc/modules`" = "" ]; then
echo "speakup_soft start=1" >> /etc/modules
fi

# Enable speech-dispatcher to run system-wide
sed -i 's/RUN_SPEECHD=no/RUN_SPEECHD=yes/' /etc/default/speech-dispatcher

# Edit speechd.conf to enable ibmtts.
sed -i 's/#AddModule "ibmtts"/AddModule "ibmtts"/' /etc/speech-dispatcher/speechd.conf

# Enable brltty for Braille displays
sed -i 's/^RUN_BRLTTY=.*/RUN_BRLTTY=yes/' /etc/default/brltty

# Needed to enable Orca to access root applications
if [ "`grep 'ORBIT_SOCKETDIR XDG_SESSION_COOKIE GTK_MODULES' /etc/sudoers`" = "" ]; then
    sed -i -e 's/# Host alias specification/Defaults\tenv_keep = "ORBIT_SOCKETDIR XDG_SESSION_COOKIE GTK_MODULES"\n\n# Host alias specification/g' /etc/sudoers
fi

# Edit speechd.conf to enable ibmtts.
if [ -f ~/.speech-dispatcher/conf/speechd.conf ]; then
    sed -i 's/#AddModule "ibmtts"/AddModule "ibmtts"/' ~/.speech-dispatcher/conf/speechd.conf
fi
