#!/bin/bash
#
# This script can be run to switch pulseaudio into system mode - restart required
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Stage 0 - Declare text colour/system bell functions

function black {
    tput setf 0   
}

function green {
    tput setf 2    
}

function blue {
    tput setf 3
}

function red {
    tput setf 4    
}

function white {
    tput setf 7
}

function reset {
    tput reset
}

function bell {
    echo -en "\007"    
}

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Stage 1 - Configure PulseAudio

# Set pulseaudio to run as system-wide daemon.

echo
blue
echo "Setting pulseaudio to run system-wide..."
green
echo

sed -i 's/PULSEAUDIO_SYSTEM_START=0/PULSEAUDIO_SYSTEM_START=1/' /etc/default/pulseaudio
sed -i 's/^ *; *autospawn *= *yes *$/autospawn = no/' /etc/pulse/client.conf
rm -f /etc/xdg/autostart/pulseaudio.desktop
sed -i 's/load-module module-native-protocol-unix$/load-module module-native-protocol-unix auth-anonymous=1/' /etc/pulse/system.pa
if [ "`grep 'sleep 2.0' /etc/init.d/pulseaudio`" = "" ];then
sed -i 's/\tstart-stop-daemon\(.*\)--start/\tsleep 2.0\n\tstart-stop-daemon\1--start/' /etc/init.d/pulseaudio
fi

shutdown -r now
