#!/bin/bash

sed -i 's/PULSEAUDIO_SYSTEM_START=1/PULSEAUDIO_SYSTEM_START=0/' /etc/default/pulseaudio

sed -i 's/^ *; *autospawn = no/autospawn = yes/' /etc/pulse/client.conf 

cp /usr/share/vinux/pulseaudio.desktop /etc/xdg/autostart/pulseaudio.desktop 


