#!/bin/bash

# This script can be run to switch pulseaudio into user mode - restart required.
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Stage 0 - Declare text colour/system bell functions

function black {
    tput setf 0   
}

function green {
    tput setf 2    
}

function blue {
    tput setf 3
}

function red {
    tput setf 4    
}

function white {
    tput setf 7
}

function reset {
    tput reset
}

function bell {
    echo -en "\007"    
}

echo
blue
echo "Setting pulseaudio to run in user mode..."
green
echo

sed -i 's/PULSEAUDIO_SYSTEM_START=1/PULSEAUDIO_SYSTEM_START=0/' /etc/default/pulseaudio

sed -i 's/^ *; *autospawn = no/autospawn = yes/' /etc/pulse/client.conf 

cp /usr/share/vinux/pulseaudio.desktop /etc/xdg/autostart/pulseaudio.desktop 

sed -i".bak" '/sleep 3/d' /etc/init.d/pulseaudio

shutdown -r now
