#!/bin/bash
#
# This script can be run anytime to restore speech to a working state on a system.  
# Speech currently is often broken by system updates from Ubuntu. To run the script
# type: 'sudo restorespeech'.
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Stage 0 - Declare text colour/system bell functions

function black {
    tput setf 0   
}

function green {
    tput setf 2    
}

function blue {
    tput setf 3
}

function red {
    tput setf 4    
}

function white {
    tput setf 7
}

function reset {
    tput reset
}

function bell {
    echo -en "\007"    
}

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Stage 1 - Configure PulseAudio

# Set pulseaudio to run as system-wide daemon.

echo
bell
red
echo -n "Do you want to run speakup and pulseaudio as a system service? [y/n]: "; read ANSWER
green
echo

if [ "$ANSWER" = "y" ]; then   

echo
blue
echo "Setting pulseaudio to run system-wide..."
green
echo

sed -i 's/PULSEAUDIO_SYSTEM_START=0/PULSEAUDIO_SYSTEM_START=1/' /etc/default/pulseaudio
sed -i 's/^ *; *autospawn *= *yes *$/autospawn = no/' /etc/pulse/client.conf
rm -f /etc/xdg/autostart/pulseaudio.desktop
sed -i 's/load-module module-native-protocol-unix$/load-module module-native-protocol-unix auth-anonymous=1/' /etc/pulse/system.pa
sed -i 's/^OnlyShowIn=XFCE;$/OnlyShowIn=GNOME;XFCE;/' /etc/xdg/autostart/gnome-volume-control-applet.desktop
if [ "`grep 'sleep 3' /etc/init.d/pulseaudio`" = "" ];then
sed -i 's/\tstart-stop-daemon\(.*\)--start/\tsleep 3\n\tstart-stop-daemon\1--start/' /etc/init.d/pulseaudio
fi
fi



# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Stage 2 - Configuring Speech

# Enable speakup

echo "speakup_soft start=1" >> /etc/modules

# Enable speech-dispatcher to run system-wide
sed -i 's/RUN_SPEECHD=no/RUN_SPEECHD=yes/' /etc/default/speech-dispatcher

# Edit speechd.conf to enable ibmtts.
sed -i 's/#AddModule "ibmtts"/#AddModule "ibmtts"/' /etc/speech-dispatcher/speechd.conf

# Enable brltty for Braille displays
sed -i 's/^RUN_BRLTTY=.*/RUN_BRLTTY=yes/' /etc/default/brltty

# Needed to enable Orca to access root applications
if [ "`grep 'ORBIT_SOCKETDIR XDG_SESSION_COOKIE GTK_MODULES' /etc/sudoers`" = "" ]; then
    sed -i -e 's/# Host alias specification/Defaults\tenv_keep = "ORBIT_SOCKETDIR XDG_SESSION_COOKIE GTK_MODULES"\n\n# Host alias specification/g' /etc/sudoers
fi

# Edit speechd.conf to enable ibmtts.
if [ -f ~/.speech-dispatcher/conf/speechd.conf ]; then
    sed -i 's/#AddModule "ibmtts"/#AddModule "ibmtts"/' ~/.speech-dispatcher/conf/speechd.conf
fi

