#!/bin/bash

mkdir -p /usr/local/share/vinux/vinux--docs
cd /usr/share/vinux
if [ -d "vinux-docs" ]; then
rm -r vinux-docs
fi
git clone git://vinux-docs.git.sourceforge.net/gitroot/vinux-docs/vinux-docs
cd vinux-docs

BRANCH=`lsb_release -cs`

if [ $BRANCH == "maverick" ]; then
BRANCH="master"
fi

git checkout $BRANCH
exit=0
