#!/bin/bash

gconftool-2 --set /desktop/gnome/interface/icon_theme --type string 'Mist'
gconftool-2 --set /desktop/gnome/interface/gtk_theme --type string 'Darklooks'
gconftool-2 --set /apps/metacity/general/theme --type string 'Mist'
gconftool-2 --set /desktop/gnome/background/picture_filename --type string "/usr/share/backgrounds/Vinux-Dusk.jpg"
gconftool-2 --set /apps/metacity/general/button_layout --type string ":minimize,maximize,close"

gconftool-2 --set /apps/nautilus/preferences/desktop_font  --type string 'Sans Bold 16'
gconftool-2 --set /desktop/gnome/interface/monospace_font_name --type string 'Monospace Bold 16'
gconftool-2 --set /desktop/gnome/interface/document_font_name --type string 'Sans Bold 16'
gconftool-2 --set /desktop/gnome/interface/font_name --type string 'Sans Bold 16'
gconftool-2 --set /apps/metacity/general/titlebar_font --type string 'Sans Bold 16'

gconftool-2 --set /desktop/gnome/peripherals/mouse/cursor_size -s -t int  48
gconftool-2 --set /desktop/gnome/peripherals/mouse/cursor_theme --type string 'DMZ-White'
gconftool-2 --set /apps/compiz/general/allscreens/options/cursor_size -s -t int 48
gconftool-2 --set /apps/compiz/general/allscreens/options/cursor_theme --type string 'DMZ-White'
