#!/bin/bash

gconftool-2 --set /desktop/gnome/interface/icon_theme --type string 'Humanity-Dark'
gconftool-2 --set /desktop/gnome/interface/gtk_theme --type string 'New Wave'
gconftool-2 --set /apps/metacity/general/theme --type string 'Ambiance'
gconftool-2 --set /desktop/gnome/background/picture_filename --type string "/usr/share/backgrounds/Vinux-Dawn.jpg"
gconftool-2 --set /apps/metacity/general/button_layout --type string "close,minimize,maximize:"

gconftool-2 --set /apps/nautilus/preferences/desktop_font  --type string 'Sans Bold 12'
gconftool-2 --set /desktop/gnome/interface/monospace_font_name --type string 'Monospace Bold 12'
gconftool-2 --set /desktop/gnome/interface/document_font_name --type string 'Sans Bold 12'
gconftool-2 --set /desktop/gnome/interface/font_name --type string 'Sans Bold 12'
gconftool-2 --set /apps/metacity/general/titlebar_font --type string 'Sans Bold 12'

gconftool-2 --set /desktop/gnome/peripherals/mouse/cursor_size -s -t int  48
gconftool-2 --set /desktop/gnome/peripherals/mouse/cursor_theme --type string 'DMZ-White'
gconftool-2 --set /apps/compiz/general/allscreens/options/cursor_size -s -t int 48
gconftool-2 --set /apps/compiz/general/allscreens/options/cursor_theme --type string 'DMZ-White'
