#!/bin/bash

# last modified by Rob Whyte November 1 2011

# This script is executed by a desktop icon with gksu privellages
# It will offer options to install restricted codecs

packages='ubuntu-restricted-extras non-free-codecs libdvdcss2'
# Check for internet connectivity with 2 packets pinged to google
ping -c2 google.com >/dev/null 2>&1 
if [ $? -eq 0 ] 
then 
# connection is alive
apt-get update | zenity --progress --pulsate --auto-close --auto-kill --title "Updating package lists" --text "This may  take a few moments." | apt-get install -y --force-yes $packages | zenity --progress --pulsate --auto-close --auto-kill --text "Downloading and installing packages" --text "This may take some time, please be patient." | zenity --info --title "Completed" --text "Package installation completed"
else 
# no connection
zenity --error --text ""No internet connection detected, Please check your connection and try again
fi
