#!/bin/bash

# This is a Vinux EasyInstall script it automates the installation of a suite of applications from a desktop
# icon, which will disappear if the packages are successfully installed. The menu launchers are not removed
# so you can install the packages again if you want to update them and/or reinstall them etc. 

# Step 0: Check whether script has already been run if not go to step 9

b=$USER
a="/home/"

if [ ! -e $a$b/.Google ]; then 

# Step 1: Ask for confirmation - if cancelled go to Step 8

if zenity --question --text "Do you want to install the Vinux Google Suite? None of these applications are accessible with a screen-reader. This will install the prism-google-groups, prism-google-mail, chromium-browser, prism-google-calendar and prism-google-docs packages!"; then

# Step 2: Get user name and ask for admin password

gksu su

# Step 3: Update package list and check it was successful - if not go to Step 7

set -o pipefail ; if gksu apt-get update | zenity --progress --pulsate --auto-close --auto-kill --text="Updating package lists, please wait..." ; then

# Step 4: Update packages and check that it was successful - if not go to Step 6

set -o pipefail ; if gksu apt-get -y install prism-google-groups prism-google-mail chromium-browser prism-google-calendar prism-google-docs | zenity --progress --pulsate --auto-close --auto-kill --text="Downloading and installing packages, please wait..." ; then

touch /$a$b/.Google

# Step 5: Delete desktop icon if it still exists and display the success message

a="/home/"
c="/Desktop/EasyInstall-Google.desktop"
if [ -e $a$b$c ]; then 
rm $a$b$c
fi
zenity --info --text "Installation was successful - Press enter to finish!"

# Step 6: Execute if installation of packages fails - from Step 4

else
zenity --info --text "Installation of packages failed - Press enter to close!"
fi

# Step 7: Execute if update of package list fails - from Step 3

else
zenity --info --text "Update of package list failed - Press enter to close!"
fi

# Step 8: Execute if installation is cancelled - from Step 1

else 
zenity --info --text "Installation was cancelled - Press enter to close!"
fi

# Step 9: Remove Packages - from Step 0

elif zenity --question --text "Do you want to remove the Vinux Google Suite? This will remove the prism-google-groups, prism-google-mail, chromium-browser, prism-google-calendar and prism-google-docs packages!"; then

gksu su

set -o pipefail ; if gksu apt-get -y remove prism-google-groups prism-google-mail chromium-browser prism-google-calendar prism-google-docs | zenity --progress --pulsate --auto-close --auto-kill --text="Removing packages, please wait..." ; then

rm /$a$b/.Google

zenity --info --text "Packages were removed - Press enter to close!"

else
zenity --info --text "Package removal failed - Press enter to close!"
fi

else
zenity --info --text "Package removal cancelled - Press enter to close!"
fi

# Step 10: Exit

exit=0
