#! /bin/bash

if zenity --question --text "Do you want to install Gimp, Inkscape and Scribus?"; then

b=$USER

gksu su

gksu apt-get update | zenity --progress --pulsate --auto-close --auto-kill --text="Updating package lists, please wait..."
gksu 'apt-get -y install gimp inkscape scribus' | zenity --progress --pulsate --auto-close --auto-kill --text="Downloading and installing packages, please wait..."

if [ $? -eq 0 ]; then

a="/home/"
c="/Desktop/EasyInstall-Graphics.desktop"

if [ -e $a$b$c ]; then 
rm $a$b$c
fi

zenity --info --text "Installation successful - Press enter to finish!"

else

zenity --info --text "Installation failed - Press enter to close!"

fi

else 

zenity --info --text "Installation was cancelled - Press enter to close!"

fi

exit=0
