#!/bin/bash

# This is a Vinux EasyInstall script it automates the installation of a suite of applications from a desktop
# icon, which will disappear if the packages are successfully installed. The menu launchers are not removed
# so you can install the packages again if you want to update them and/or reinstall them etc. 

# Step 1: Ask for confirmation - if cancelled go to Step 8

if zenity --question --text "Do you want to install the Vinux Multimedia Suite? This will install the \
transmageddon, thoggen, cheese, audacity, jokosher and gtkpod packages!"; then

# Step 2: Get user name and ask for admin password

b=$USER
gksu su

# Step 3: Update package list and check it was successful - if not go to Step 7

set -o pipefail ; if gksu apt-get update | zenity --progress --pulsate --auto-close --auto-kill --text="Updating package lists, please wait..." ; then

# Step 4: Update packages and check that it was successful - if not go to Step 6

set -o pipefail ; if gksu apt-get -y install transmageddon thoggen cheese audacity jokosher gtkpod | zenity --progress --pulsate --auto-close --auto-kill --text="Downloading and installing packages, please wait..." ; then

# Step 5: Delete desktop icon if it still exists and display the success message

a="/home/"
c="/Desktop/EasyInstall-Multimedia.desktop"
if [ -e $a$b$c ]; then 
rm $a$b$c
fi
zenity --info --text "Installation was successful - Press enter to finish!"

# Step 6: Execute if installation of packages fails - from Step 4

else
zenity --info --text "Installation of packages failed - Press enter to close!"
fi

# Step 7: Execute if update of package list fails - from Step 3

else
zenity --info --text "Update of package list failed - Press enter to close!"
fi

# Step 8: Execute if installation is cancelled - from Step 1

else 
zenity --info --text "Installation was cancelled - Press enter to close!"
fi

# Step 9: Exit

exit=0
