#! /bin/bash

sudo apt-get update
sudo apt-get install openoffice.org openoffice.org-gnome evolution evolution-exchange

if [ $? -eq 0 ]; then

app="/Desktop/EasyInstall-Office.desktop"
rm -f /home/$USER/Desktop/$app
rm -f /home/$USER/.local/share/applications/$app
sudo rm -f /etc/skel/Destop/$app
sudo rm -f /etc/skel/.local/share/applications/$app

echo "Installation Successful - Press any key to quit!"
read input

else

echo "Installation Failed - Press any key to quit!"
read input

fi
